In [43]:
import numpy as np
from scipy import stats

X1 = np . array ([1 ,4 ,9 ,11 ,3 ,8 ,5 ,10 ,2 ,7 ,6] , dtype = float )
X2 = np . array ([8 ,2 , -8 , -10 ,6 , -6 ,0 ,12 ,4 , -2 , -4] , dtype = float )
y = np . array ([6 ,8 ,1 ,0 ,5 ,3 ,2 , -4 ,10 , -3 ,5] , dtype = float )

In [21]:
n=len(y)

X=np.column_stack([np.ones(n),X1,X2])
k=X.shape[1]

In [38]:
beta_hat = np.linalg.pinv(X) @ y
beta_hat

array([10.66905536, -1.27128295, -0.22746716])

In [23]:
y_hat = X @ beta_hat
y_hat

array([ 7.57803516,  5.12898925,  1.04724606, -1.04038552,  5.49040358,
        1.8635947 ,  4.31264061, -4.77338   ,  7.21662084,  2.22500903,
        3.95122629])

In [24]:
e = y-y_hat
e

array([-1.57803516,  2.87101075, -0.04724606,  1.04038552, -0.49040358,
        1.1364053 , -2.31264061,  0.77338   ,  2.78337916, -5.22500903,
        1.04877371])

In [29]:
ss_res = np.sum((y-y_hat)**2)
ss_res

np.float64(55.443713023914675)

In [32]:
ss_reg = np.sum((y_hat-np.mean(y))**2)
ss_reg

np.float64(134.55628697608535)

In [33]:
ss_tot = ss_reg+ss_res
ss_tot

np.float64(190.00000000000003)

In [39]:
ms_res = ss_res/(n-k)
ms_reg = ss_reg/(k-1)
F=ms_reg/ms_res
F

np.float64(9.707595659623074)

In [48]:
xtx_inv = np.linalg.pinv(X.T @ X)
se = np.sqrt(ms_res*np.diag(xtx_inv))
t_vals = beta_hat/se
t_crit = stats.t.ppf(0.025,8)
t_crit, t_vals


(np.float64(-2.3060041352041662),
 array([ 5.51067954, -4.35176279, -1.63269409]))

In [52]:
F_crit = stats.f.ppf(1-0.05,2,8)
F_crit, F

(np.float64(4.458970107524511), np.float64(9.707595659623074))